import tweepy, csv, time

# keys generated by Twitter App registration
consumer_key = 'wFRNosYy0eK6ph2pRIKwMybqe'
consumer_secret = 'HU4N6iBn1NqI3LEx7L6hVYsBZp08WfANwBKnzt9hy97gBBiEjp'
access_token = '1287375775-3x7S7mWHVrXkIc8ZFEemRkVCpjdn5aXbhyxKf9H'
access_token_secret = '0kTiFLNlqcuzjGkBH5rz02caxsVYAUPs6WOaoCrWmmMv5'

# authenticating app with API keys
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
followers = api.friends
the_donald = api.get_user(screen_name='realDonaldTrump')
tweets = 0

# opens csv file
tweetwriter = csv.writer(open('data.csv', 'w'), delimiter=',')

# loops through tweets in timeline, pauses on rate limit error
for p in range(1, int((the_donald.statuses_count)/20)):
	try:
		for i in api.user_timeline(screen_name='realDonaldTrump', page = p):
			tweet = api.get_status(i.id, tweet_mode='extended')
			tweet_text = tweet._json['full_text']
			if('http' in tweet_text):
				tweet_text = tweet_text[:tweet_text.find('http')]
			tweet_time = tweet.created_at

			# writes to csv file if tweet is not retweet
			if(not (tweet_text[:2] == 'RT')):
				tweetwriter.writerow([tweet_text,tweet_time])
				print(tweet_text) 
				print('\t %s - Tweet #%i\n' % (str(tweet_time), tweets))
			tweets += 1
	except tweepy.RateLimitError:
			print('rate limit error!\n')
			time.sleep(15 * 60)
			continue
	print('Page #'+str(p)+'\n')
print("ALL DONE!!!")


# TODO: fix problem w/ printing only page # after ~1600 tweets
