import tweepy, csv, time

# keys generated by Twitter App registration
consumer_key = 'wFRNosYy0eK6ph2pRIKwMybqe'
consumer_secret = 'HU4N6iBn1NqI3LEx7L6hVYsBZp08WfANwBKnzt9hy97gBBiEjp'
access_token = '1287375775-3x7S7mWHVrXkIc8ZFEemRkVCpjdn5aXbhyxKf9H'
access_token_secret = '0kTiFLNlqcuzjGkBH5rz02caxsVYAUPs6WOaoCrWmmMv5'

# authenticating app with API keys
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
followers = api.friends
the_donald = api.get_user(screen_name='realDonaldTrump')
tweets = 0

# opens csv file
tweetwriter = csv.writer(open('data.csv', 'w'), delimiter=',')
print(str(the_donald.statuses_count))

# loops through tweets in timeline, pauses on rate limit error
for i in tweepy.Cursor(api.user_timeline, id = 'realDonaldTrump').items():
	try:
		tweet = api.get_status(i.id, tweet_mode='extended')
		tweet_text = tweet._json['full_text']

		#trims links to media from tweets
		if('http' in tweet_text):
			tweet_text = tweet_text[:tweet_text.find('http')]

		#writes to csv if tweet is not retweet
		if(not (tweet_text[:2] == 'RT')):
			tweetwriter.writerow([tweet_text,tweet_time])
			tweet_time = tweet.created_at
			print(tweet_text) 
			print('\t %s - Tweet #%i\n' % (str(tweet_time), tweets))
			tweets += 1

	except tweepy.RateLimitError:
		print('rate limit error!\n')
		time.sleep(15 * 60)
		continue
print("ALL DONE!!!")


# TODO: fix problem w/ printing only page # after ~1600 tweets
