'''
	main.py
	Noah Snelson
	Main file in canary project responsbile for launching bot and posting
	statuses generated by Trainer based upon scraped text and post times.
'''
import  scrape, train, tweepy, csv, datetime, numpy, time
from datetime import datetime

fileName = 'data.csv'
tweetWriter = csv.writer(open(fileName, 'w'), delimiter=',')
crawl = scrape.Crawler(tweetWriter)
crawl.crawlTimeline()

brain = train.Trainer(csvFile=fileName)
brain.generateTimes()

while True :
	now = datetime.now()
	nowMinutes = (now.hour*60)+now.minute
	if(nowMinutes % 5 ==0):
	# prints current time every 5 mins
		print('CURRENT TIME (mins, standard): %i, %s' % (nowMinutes, str(now)))

	# if current time matches schedules post time, post tweet
	if(str(nowMinutes) in brain.postTimes):
		postText = brain.generateTweet()
		print('POSTING TWEET: \n\t' + postText)
		crawl.api.update_status(postText)
		print('POST SUCCESS\n')
	
	# generates new times every day at midnight
	if(nowMinutes == 0):
		brain.generateTimes()

	time.sleep(60)


